/* SIMPLEXSKOLLA Subjects Management - local UI prototype */

const MOCK_SUBJECTS = [
    { id: "SUB-001", code: "MTH", name: "Mathematics", category: "Core", academicLevel: "Junior Secondary", department: "Science", classes: "JSS1 A, JSS1 B, JSS2 A", status: "Active" },
    { id: "SUB-002", code: "ENG", name: "English Language", category: "Core", academicLevel: "Junior Secondary", department: "Arts", classes: "JSS1 A, JSS2 B, JSS3 A", status: "Active" },
    { id: "SUB-003", code: "BIO", name: "Biology", category: "Core", academicLevel: "Senior Secondary", department: "Science", classes: "SS1 A, SS2 A, SS3 A", status: "Active" },
    { id: "SUB-004", code: "CHM", name: "Chemistry", category: "Core", academicLevel: "Senior Secondary", department: "Science", classes: "SS1 B, SS2 B, SS3 B", status: "Active" },
    { id: "SUB-005", code: "PHY", name: "Physics", category: "Core", academicLevel: "Senior Secondary", department: "Science", classes: "SS1 A, SS2 A, SS3 B", status: "Active" },
    { id: "SUB-006", code: "ECO", name: "Economics", category: "Elective", academicLevel: "Senior Secondary", department: "Commercial", classes: "SS1 A, SS2 B, SS3 A", status: "Active" },
    { id: "SUB-007", code: "GOV", name: "Government", category: "Elective", academicLevel: "Senior Secondary", department: "Arts", classes: "SS1 B, SS2 A, SS3 B", status: "Active" },
    { id: "SUB-008", code: "LIT", name: "Literature in English", category: "Elective", academicLevel: "Senior Secondary", department: "Arts", classes: "SS1 A, SS2 A, SS3 A", status: "Active" },
    { id: "SUB-009", code: "GEO", name: "Geography", category: "Elective", academicLevel: "Senior Secondary", department: "Arts", classes: "SS1 B, SS2 B", status: "Active" },
    { id: "SUB-010", code: "CVE", name: "Civic Education", category: "General", academicLevel: "Senior Secondary", department: "General", classes: "SS1 A, SS2 A, SS3 A", status: "Active" },
    { id: "SUB-011", code: "CST", name: "Computer Studies", category: "General", academicLevel: "Junior Secondary", department: "General", classes: "JSS1 A, JSS2 A, JSS3 B", status: "Active" },
    { id: "SUB-012", code: "BSC", name: "Basic Science", category: "Core", academicLevel: "Junior Secondary", department: "Science", classes: "JSS1 B, JSS2 B, JSS3 A", status: "Active" },
    { id: "SUB-013", code: "BTE", name: "Basic Technology", category: "Core", academicLevel: "Junior Secondary", department: "Vocational", classes: "JSS1 A, JSS2 A, JSS3 A", status: "Active" },
    { id: "SUB-014", code: "AGS", name: "Agricultural Science", category: "Elective", academicLevel: "Junior Secondary", department: "Vocational", classes: "JSS1 B, JSS2 B", status: "Active" },
    { id: "SUB-015", code: "CRS", name: "Christian Religious Studies", category: "General", academicLevel: "Senior Secondary", department: "Arts", classes: "SS1 A, SS2 A", status: "Active" },
    { id: "SUB-016", code: "PHE", name: "Physical and Health Education", category: "General", academicLevel: "Junior Secondary", department: "General", classes: "JSS1 A, JSS2 B, JSS3 B", status: "Active" },
    { id: "SUB-017", code: "FMT", name: "Further Mathematics", category: "Elective", academicLevel: "Senior Secondary", department: "Science", classes: "SS1 A, SS2 A", status: "Active" },
    { id: "SUB-018", code: "COM", name: "Commerce", category: "Elective", academicLevel: "Senior Secondary", department: "Commercial", classes: "SS1 B, SS2 B, SS3 B", status: "Active" },
    { id: "SUB-019", code: "FAC", name: "Financial Accounting", category: "Elective", academicLevel: "Senior Secondary", department: "Commercial", classes: "SS1 A, SS2 A, SS3 A", status: "Active" },
    { id: "SUB-020", code: "DPR", name: "Data Processing", category: "Vocational", academicLevel: "Senior Secondary", department: "Vocational", classes: "SS1 B, SS2 B", status: "Active" },
    { id: "SUB-021", code: "HIS", name: "History", category: "Elective", academicLevel: "Senior Secondary", department: "Arts", classes: "SS1 A, SS2 A", status: "Inactive" },
    { id: "SUB-022", code: "MUS", name: "Music", category: "Elective", academicLevel: "Junior Secondary", department: "Arts", classes: "JSS1 B, JSS2 B", status: "Inactive" },
    { id: "SUB-023", code: "FRE", name: "French", category: "General", academicLevel: "Junior Secondary", department: "Arts", classes: "JSS1 A, JSS3 A", status: "Active" },
    { id: "SUB-024", code: "ENT", name: "Entrepreneurship", category: "Vocational", academicLevel: "Senior Secondary", department: "Commercial", classes: "SS2 B, SS3 B", status: "Inactive" }
];

const subjectState = { subjects: [...MOCK_SUBJECTS], filtered: [], page: 1, pageSize: 8, editingId: null };

function initializeSubjects() {
    const menuToggle = document.querySelector(".menu-toggle");
    const sidebar = document.querySelector(".sidebar");
    const overlay = document.querySelector(".overlay");
    menuToggle?.addEventListener("click", () => { sidebar?.classList.toggle("show"); overlay?.classList.toggle("active"); sidebar?.classList.toggle("open"); });
    overlay?.addEventListener("click", () => { sidebar?.classList.remove("show", "open"); overlay.classList.remove("active"); });
    document.getElementById("subjectSearch").addEventListener("input", updateSubjectResults);
    document.getElementById("headerSearch").addEventListener("input", event => { document.getElementById("subjectSearch").value = event.target.value; updateSubjectResults(); });
    ["categoryFilter", "levelFilter", "departmentFilter", "statusFilter"].forEach(id => document.getElementById(id).addEventListener("change", updateSubjectResults));
    document.getElementById("addSubjectButton").addEventListener("click", openAddSubjectModal);
    document.getElementById("exportButton").addEventListener("click", exportSubjects);
    document.getElementById("resetEmptyButton").addEventListener("click", resetFilters);
    document.getElementById("subjectForm").addEventListener("submit", saveSubject);
    document.querySelectorAll("[data-close-modal]").forEach(button => button.addEventListener("click", closeSubjectModal));
    document.querySelectorAll("[data-close-view]").forEach(button => button.addEventListener("click", closeViewModal));
    document.addEventListener("keydown", event => { if (event.key === "Escape") { closeSubjectModal(); closeViewModal(); } });
    updateSubjectResults();
}

function getSubjectFilters() { return { search: document.getElementById("subjectSearch").value.trim().toLowerCase(), category: document.getElementById("categoryFilter").value, level: document.getElementById("levelFilter").value, department: document.getElementById("departmentFilter").value, status: document.getElementById("statusFilter").value }; }
function filterSubjects() { const filters = getSubjectFilters(); subjectState.filtered = subjectState.subjects.filter(item => { const searchable = [item.id, item.code, item.name, item.category, item.academicLevel, item.department].join(" ").toLowerCase(); return (!filters.search || searchable.includes(filters.search)) && (!filters.category || item.category === filters.category) && (!filters.level || item.academicLevel === filters.level) && (!filters.department || item.department === filters.department) && (!filters.status || item.status === filters.status); }); return subjectState.filtered; }
function updateSubjectResults() { filterSubjects(); subjectState.page = 1; renderSubjectSummary(); renderSubjects(); renderSubjectPagination(); }
function renderSubjectSummary() { document.getElementById("totalSubjects").textContent = subjectState.subjects.length; document.getElementById("activeSubjects").textContent = subjectState.subjects.filter(item => item.status === "Active").length; document.getElementById("coreSubjects").textContent = subjectState.subjects.filter(item => item.category === "Core").length; document.getElementById("electiveSubjects").textContent = subjectState.subjects.filter(item => item.category === "Elective").length; }
function renderSubjects() { const body = document.getElementById("subjectsBody"); const start = (subjectState.page - 1) * subjectState.pageSize; const pageItems = subjectState.filtered.slice(start, start + subjectState.pageSize); body.innerHTML = pageItems.map(item => `<tr><td class="subject-id">${escapeSubject(item.id)}</td><td class="subject-code">${escapeSubject(item.code)}</td><td class="subject-name">${escapeSubject(item.name)}</td><td>${escapeSubject(item.category)}</td><td>${escapeSubject(item.academicLevel)}</td><td>${escapeSubject(item.department)}</td><td class="classes-value" title="${escapeSubject(item.classes)}">${escapeSubject(item.classes)}</td><td><span class="status-badge ${item.status === "Active" ? "status-active" : "status-inactive"}">${item.status}</span></td><td><div class="row-actions"><button class="row-action" type="button" title="View ${escapeSubject(item.id)}" aria-label="View ${escapeSubject(item.id)}" data-action="view" data-id="${item.id}"><i class="fa-solid fa-eye"></i></button><button class="row-action" type="button" title="Edit ${escapeSubject(item.id)}" aria-label="Edit ${escapeSubject(item.id)}" data-action="edit" data-id="${item.id}"><i class="fa-solid fa-pen"></i></button><button class="row-action archive" type="button" title="Deactivate ${escapeSubject(item.id)}" aria-label="Deactivate ${escapeSubject(item.id)}" data-action="archive" data-id="${item.id}"><i class="fa-solid fa-box-archive"></i></button></div></td></tr>`).join(""); document.getElementById("emptyState").hidden = pageItems.length > 0; body.querySelectorAll("[data-action='view']").forEach(button => button.addEventListener("click", () => viewSubject(button.dataset.id))); body.querySelectorAll("[data-action='edit']").forEach(button => button.addEventListener("click", () => openEditSubjectModal(button.dataset.id))); body.querySelectorAll("[data-action='archive']").forEach(button => button.addEventListener("click", () => archiveSubject(button.dataset.id))); const shownStart = subjectState.filtered.length ? start + 1 : 0; const shownEnd = Math.min(start + subjectState.pageSize, subjectState.filtered.length); document.getElementById("paginationSummary").textContent = `Showing ${shownStart}-${shownEnd} of ${subjectState.filtered.length} subjects`; }
function renderSubjectPagination() { const pagination = document.getElementById("pagination"); const pages = Math.max(1, Math.ceil(subjectState.filtered.length / subjectState.pageSize)); subjectState.page = Math.min(subjectState.page, pages); pagination.innerHTML = `<button class="page-button" type="button" data-page="prev" aria-label="Previous page" ${subjectState.page === 1 ? "disabled" : ""}><i class="fa-solid fa-chevron-left"></i></button>${Array.from({ length: pages }, (_, index) => `<button class="page-button ${subjectState.page === index + 1 ? "active" : ""}" type="button" data-page="${index + 1}">${index + 1}</button>`).join("")}<button class="page-button" type="button" data-page="next" aria-label="Next page" ${subjectState.page === pages ? "disabled" : ""}><i class="fa-solid fa-chevron-right"></i></button>`; pagination.querySelectorAll("[data-page]").forEach(button => button.addEventListener("click", () => { const page = button.dataset.page; if (page === "prev") subjectState.page--; else if (page === "next") subjectState.page++; else subjectState.page = Number(page); renderSubjects(); renderSubjectPagination(); })); }
function openAddSubjectModal() { subjectState.editingId = null; document.getElementById("subjectModalTitle").textContent = "Add Subject"; document.getElementById("subjectForm").reset(); document.getElementById("subjectStatus").value = "Active"; clearSubjectErrors(); showModal("subjectModal"); document.getElementById("subjectName").focus(); }
function openEditSubjectModal(id) { const item = subjectState.subjects.find(record => record.id === id); if (!item) return; subjectState.editingId = id; document.getElementById("subjectModalTitle").textContent = "Edit Subject"; document.getElementById("subjectRecordId").value = item.id; document.getElementById("subjectName").value = item.name; document.getElementById("subjectCode").value = item.code; document.getElementById("subjectCategory").value = item.category; document.getElementById("subjectLevel").value = item.academicLevel; document.getElementById("subjectDepartment").value = item.department; document.getElementById("subjectClasses").value = item.classes; document.getElementById("subjectStatus").value = item.status; clearSubjectErrors(); showModal("subjectModal"); document.getElementById("subjectName").focus(); }
function saveSubject(event) { event.preventDefault(); const fields = { subjectName: document.getElementById("subjectName"), subjectCode: document.getElementById("subjectCode"), subjectCategory: document.getElementById("subjectCategory"), subjectLevel: document.getElementById("subjectLevel"), subjectDepartment: document.getElementById("subjectDepartment") }; let valid = true; Object.entries(fields).forEach(([id, field]) => { if (!field.value.trim()) { setSubjectError(id, "This field is required."); valid = false; } else clearSubjectError(id); }); if (!valid) return; const record = { name: fields.subjectName.value.trim(), code: fields.subjectCode.value.trim().toUpperCase(), category: fields.subjectCategory.value, academicLevel: fields.subjectLevel.value, department: fields.subjectDepartment.value, classes: document.getElementById("subjectClasses").value.trim() || "Not assigned", status: document.getElementById("subjectStatus").value }; if (subjectState.editingId) { Object.assign(subjectState.subjects.find(item => item.id === subjectState.editingId), record); showToast("Subject updated successfully."); } else { const nextNumber = subjectState.subjects.length + 1; record.id = `SUB-${String(nextNumber).padStart(3, "0")}`; subjectState.subjects.push(record); showToast("Subject added successfully."); } closeSubjectModal(); updateSubjectResults(); }
function viewSubject(id) { const item = subjectState.subjects.find(record => record.id === id); if (!item) return; document.getElementById("viewModalTitle").textContent = item.name; document.getElementById("viewDetails").innerHTML = [["Subject ID", item.id], ["Subject Code", item.code], ["Subject Name", item.name], ["Category", item.category], ["Academic Level", item.academicLevel], ["Department", item.department], ["Classes", item.classes], ["Status", item.status]].map(([label, value]) => `<div class="view-item"><span>${label}</span><strong>${escapeSubject(String(value))}</strong></div>`).join(""); showModal("viewModal"); }
function archiveSubject(id) { const item = subjectState.subjects.find(record => record.id === id); if (!item) return; if (!window.confirm(`${item.status === "Active" ? "Deactivate" : "Activate"} ${item.name}?`)) return; item.status = item.status === "Active" ? "Inactive" : "Active"; showToast(`Subject ${item.status === "Active" ? "activated" : "deactivated"} locally.`); updateSubjectResults(); }
function exportSubjects() { const rows = filterSubjects(); if (!rows.length) { showToast("There are no subjects to export.", true); return; } const headers = ["Subject ID", "Subject Code", "Subject Name", "Category", "Academic Level", "Department", "Classes", "Status"]; const csv = [headers, ...rows.map(item => [item.id, item.code, item.name, item.category, item.academicLevel, item.department, item.classes, item.status])].map(row => row.map(value => `"${String(value).replace(/"/g, '""')}"`).join(",")).join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8;" })); link.download = "simplexskolla-subjects.csv"; link.click(); URL.revokeObjectURL(link.href); showToast("Subject directory exported."); }
function resetFilters() { document.getElementById("subjectSearch").value = ""; document.getElementById("headerSearch").value = ""; ["categoryFilter", "levelFilter", "departmentFilter", "statusFilter"].forEach(id => { document.getElementById(id).value = ""; }); updateSubjectResults(); }
function showModal(id) { document.getElementById(id).hidden = false; document.body.classList.add("modal-open"); }
function closeSubjectModal() { document.getElementById("subjectModal").hidden = true; document.body.classList.remove("modal-open"); }
function closeViewModal() { document.getElementById("viewModal").hidden = true; document.body.classList.remove("modal-open"); }
function setSubjectError(id, message) { document.getElementById(id)?.closest(".field")?.classList.add("invalid"); const error = document.querySelector(`[data-error-for="${id}"]`); if (error) error.textContent = message; }
function clearSubjectError(id) { document.getElementById(id)?.closest(".field")?.classList.remove("invalid"); const error = document.querySelector(`[data-error-for="${id}"]`); if (error) error.textContent = ""; }
function clearSubjectErrors() { document.querySelectorAll(".field").forEach(field => field.classList.remove("invalid")); document.querySelectorAll(".field-error").forEach(error => { error.textContent = ""; }); }
function showToast(message, error = false) { const toast = document.getElementById("toast"); document.getElementById("toastMessage").textContent = message; toast.classList.toggle("error", error); toast.classList.add("show"); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove("show"), 3300); }
function escapeSubject(value) { return value.replace(/[&<>\"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;" }[character])); }

document.addEventListener("DOMContentLoaded", initializeSubjects);
